- name: Install dependencies
  run: npm install
  working-directory: frontend/frontend

- name: Run lint
  run: npm run lint
  working-directory: frontend/frontend

- name: Run tests
  run: npm run test:ci
  working-directory: frontend/frontend

- name: Build frontend
  run: npm run build
  working-directory: frontend/frontend
